[package]
name = "athena-vm-sdk"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
athena-vm = { path = "../entrypoint" }
athena-hostfunctions = { path = "../hostfunctions" }
athena-interface = { path = "../../interface" }
borsh = "1.5.1"
borsh-derive = "1.5.1"
cfg-if = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
