[package]
name = "athena-vm-sdk"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
athena-vm = { path = "../entrypoint" }
athena-hostfunctions = { path = "../hostfunctions" }
athena-interface = { path = "../../interface" }
serde = { version = "1.0", features = ["derive"] }
