name: Test setup
inputs:
  pull_token:
    description: "Token to use for private repo access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up git private repo access
      shell: bash
      run: |
        git config --global url."https://${{ inputs.pull_token }}@github.com/".insteadOf ssh://git@github.com
        git config --global url."https://${{ inputs.pull_token }}@github.com".insteadOf https://github.com

    - name: Install Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
        cache-dependency-path: "**/go.sum"

    - name: Print go version
      shell: bash
      run: go version

    - name: Setup Rust toolchain
      id: rustc-toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy, rustfmt
        cache: false
