[workspace]
members = [
  "cli",
  "core",
  "ffi/athcon/bindings/rust/athcon-client",
  "ffi/athcon/bindings/rust/athcon-sys",
  "ffi/athcon/bindings/rust/athcon-vm",
  "ffi/ffitest",
  "ffi/vmlib",
  "helper",
  "interface",
  "runner",
  "sdk",
  "vm/entrypoint",
  "vm/precompiles",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Lane Rettig <lane@spacemesh.io>"]
repository = "https://github.com/athenavm/athena"
homepage = "https://www.athenavm.org/"
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
