[workspace]
members = [
  "athcon/bindings/rust/athcon-host",
  "athcon/bindings/rust/athcon-sys",
  "athcon/bindings/rust/athcon-vm",
  "cli",
  "core",
  "helper",
  "runner",
  "sdk",
  "vm/entrypoint",
  "vm/precompiles",
]
exclude = ["examples/target"]
resolver = "2"

[workspace.dependencies]
