[package]
version = "0.1.0"
name = "hello_world-script"
edition = "2021"

[dependencies]
athena-sdk = { path = "../../../sdk" }
tracing-subscriber = "0.3.18"

[build-dependencies]
athena-builder = { path = "../../../builder" }
