[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"

[[bin]]
name = "test_program"
path = "src/main.rs"
