[package]
edition = "2021"
name = "athena-core"
version = "0.1.0"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive", "rc"] }
elf = "0.7.4"
log = "0.4.21"
nohash-hasher = "0.2.0"
rrs-lib = { git = "https://github.com/GregAC/rrs.git" }

cfg-if = "1.0.0"
hex = "0.4.3"
serde_with = "3.8.1"
tracing = "0.1.40"
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }
tracing-subscriber = { version = "0.3.18", features = ["std", "env-filter"] }
strum_macros = "0.26"
strum = "0.26"
thiserror = "1.0.60"

[dev-dependencies]
athena-vm = { path = "../vm/entrypoint" }

[features]
debug = []
