[package]
edition = "2021"
name = "athena-core"
version = "0.1.0"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive", "rc"] }
elf = "0.7.4"
itertools = "0.13.0"
log = "0.4.21"
nohash-hasher = "0.2.0"
num = { version = "0.4.3" }
rrs-lib = { git = "https://github.com/GregAC/rrs.git" }

anyhow = "1.0.83"
arrayref = "0.3.7"
cfg-if = "1.0.0"
generic-array = { version = "1.0.0", features = ["alloc", "serde"] }
typenum = "1.17.0"
hex = "0.4.3"
num_cpus = "1.16.0"
serde_with = "3.8.1"
size = "0.4.1"
tempfile = "3.10.1"
tracing = "0.1.40"
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }
tracing-subscriber = { version = "0.3.18", features = ["std", "env-filter"] }
strum_macros = "0.26"
strum = "0.26"
web-time = "1.1.0"
rayon-scan = "0.1.1"
thiserror = "1.0.60"
num-bigint = { version = "0.4.3", default-features = false }

[dev-dependencies]
criterion = "0.5.1"
num = { version = "0.4.3", features = ["rand"] }
rand = "0.8.5"
athena-vm = { path = "../vm/entrypoint" }

[features]
debug = []
