[package]
name = "athena-core"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
athena-interface = { path = "../interface" }
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive", "rc"] }
elf = "0.7.4"
log = "0.4.22"
nohash-hasher = "0.2.0"
rrs-lib = { git = "https://github.com/GregAC/rrs.git" }
cfg-if = "1.0.0"
hex = "0.4.3"
serde_with = "3.9.0"
tracing = "0.1.40"
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }
tracing-subscriber = { version = "0.3.18", features = ["std", "env-filter"] }
strum_macros = "0.26"
strum = "0.26"
thiserror = "1.0.60"

[dev-dependencies]
athena-vm = { path = "../vm/entrypoint" }
athena-vm-sdk = { path = "../vm/sdk" }
borsh = "1.5.1"
wallet-common = { path = "../examples/wallet/common" }

[features]
debug = []
