change-id = 116881

[build]
target = ["riscv32em-athena-zkvm-elf"]
extended = true
tools = ["cargo", "cargo-clippy", "clippy", "rustfmt"]
configure-args = []

[rust]
lld = true
llvm-tools = true
channel = "nightly"

[llvm]
download-ci-llvm = false
