[package]
name = "athena-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
athena-precompiles = { path = "../precompiles" }
bincode = "1.3.3"
cfg-if = "1.0.0"
serde = { version = "1.0.201", features = ["derive"] }

[features]
interface = []
verify = []
