[package]
name = "athena-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
athena-precompiles = { path = "../precompiles" }
bincode = "1.3.3"
cfg-if = "1.0.0"
getrandom = { version = "0.2.14", features = ["custom"] }
serde = { version = "1.0.201", features = ["derive"] }
rand = "0.8.5"

[features]
interface = []
rv32e = []
verify = []
