[package]
name = "athena-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
athena-precompiles = { path = "../precompiles" }
bincode = "1.3.3"
cfg-if = "1.0.0"
getrandom = { version = "0.2.14", features = ["custom"] }
k256 = { version = "0.13.3", features = ["ecdsa", "std", "bits"] }
once_cell = "1.19.0"
rand = "0.8.5"
serde = { version = "1.0.201", features = ["derive"] }
sha2 = { version = "0.10.8" }

[features]
verify = [
]
