[workspace]
members = [
  "contract_template",
  "fibonacci/script",
  "hello_world/script",
  "io/script", "token/mint", "token/wallet",
  "wallet/script",
]
resolver = "2"

exclude = ["wallet/program"]
