[package]
name = "athena-interface"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
blake3 = "1.5.3"
bytemuck = "1.20.0"
hex = "0.4.3"
parity-scale-codec = { version = "3.7.0", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
tracing = "0.1.40"
mockall = "0.13.1"
