[package]
name = "athena-interface"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bincode = "1.3.3"
blake3 = "1.5.3"
bytemuck = "1.16.0"
tracing = "0.1.40"
serde = { version = "1.0.204", features = ["derive"] }
