[package]
name = "athena-interface"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
blake3 = "1.5.3"
bytemuck = "1.16.0"
log = "0.4.21"
mockall = "0.13.0"
