[package]
name = "ffitest"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
athcon-sys = { path = "../athcon/bindings/rust/athcon-sys" }
