[package]
name = "athena-sdk"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.201", features = ["derive"] }
anyhow = "1.0.83"
athena-core = { path = "../core" }
athena-interface = { path = "../interface" }
bincode = "1.3.3"
tracing = "0.1.40"
hex = "0.4.3"
log = "0.4.21"
cfg-if = "1.0"

[build-dependencies]
vergen = { version = "9", default-features = false, features = [
  "build",
  "git",
  "git2",
] }
