[package]
name = "athena-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.201", features = ["derive"] }
anyhow = "1.0.83"
athena-core = { path = "../core" }
bincode = "1.3.3"
tracing = "0.1.40"
hex = "0.4.3"
log = "0.4.21"
cfg-if = "1.0"

[build-dependencies]
vergen = { version = "8", default-features = false, features = [
  "build",
  "git",
  "git2",
] }
