[package]
name = "athena-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
twirp = { git = "https://github.com/github/twirp-rs.git", rev = "c85f31f9c54957374e7dcb3534fc52cff0aa2dc5" }
anyhow = "1.0.83"
sp1-prover = { path = "../prover", default-features = false }
athena-core = { path = "../core" }
futures = "0.3.30"
bincode = "1.3.3"
indicatif = "0.17.8"
tracing = "0.1.40"
hex = "0.4.3"
log = "0.4.21"
axum = "=0.7.5"
alloy-primitives = "0.7.0"
alloy-sol-types = "0.7.0"
sha2 = "0.10.8"
dirs = "5.0.1"
tempfile = "3.10.1"
num-bigint = "0.4.5"
cfg-if = "1.0"
ethers = { version = "2", default-features = false }

[features]
neon = ["sp1-core/neon"]
plonk = ["sp1-prover/plonk"]

[build-dependencies]
vergen = { version = "8", default-features = false, features = [
  "build",
  "git",
  "git2",
] }
