[package]
name = "athena-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
athcon-sys = { path = "../athcon/bindings/rust/athcon-sys" }
athcon-host = { path = "../athcon/bindings/rust/athcon-host" }
