[package]
name = "athena-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
athcon-client = { path = "../athcon/bindings/rust/athcon-client" }
athcon-sys = { path = "../athcon/bindings/rust/athcon-sys" }
athcon-vm = { path = "../athcon/bindings/rust/athcon-vm" }
