[package]
name = "athena-vm-declare"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
athena-vm-declare-macro = { path = "../declare-macro" }
