name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --all-features
      - name: Test cargo-athena
        working-directory: ${{ runner.temp }}
        run: |
          ${{ github.workspace }}/target/debug/cargo-athena athena new test
          cd test/program
          ${{ github.workspace }}/target/debug/cargo-athena athena build
      - name: Build examples
        run: cd examples && make
      - name: Build tests
        run: cd tests && make
      - name: Check for changes
        run:
          git diff --exit-code || (echo "Repository has uncommitted changes after building examples and tests." && exit
          1)
