#!/usr/bin/env bash

# Reference: https://github.com/foundry-rs/foundry/blob/master/foundryup/install,
# https://github.com/succinctlabs/sp1/blob/main/athup/install

set -e

echo Installing athup...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
ATHENA_DIR=${ATHENA_DIR-"$BASE_DIR/.athena"}
ATHENA_BIN_DIR="$ATHENA_DIR/bin"

BIN_URL="https://raw.githubusercontent.com/athenavm/athena/main/athup/athup"
BIN_PATH="$ATHENA_BIN_DIR/athup"

# Create the .athena bin directory and athup binary if it doesn't exist.
mkdir -p $ATHENA_BIN_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "athup: could not detect shell, manually add ${ATHENA_BIN_DIR} to your PATH."
    exit 1
esac

# Only add athup if it isn't already in PATH.
if [[ ":$PATH:" != *":${ATHENA_BIN_DIR}:"* ]]; then
    # Add the athup directory to the path and ensure the old PATH variables remain.
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$ATHENA_BIN_DIR\"" >> $PROFILE
fi

# Warn MacOS users that they may need to manually install libusb via Homebrew:
if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib && ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
    echo && echo "warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install libusb)."
fi

# Warn MacOS users that they may need to manually install opensll via Homebrew:
if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! -f /usr/local/opt/openssl/lib/libssl.3.dylib && ! -f /opt/homebrew/opt/openssl/lib/libssl.3.dylib ]]; then
    echo && echo "warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install openssl)."
fi

echo && echo "Detected your preferred shell is ${PREF_SHELL} and added athup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use athup."
echo "Then, simply run 'athup' to install Athena."
